# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


HEADERS += lon_widget/titlebar.hpp \
    ./lon_widget/button.hpp \
    ./lon_widget/messagebox.hpp \
    ./lon_widget/widget.hpp \
    $$PWD/listwidget.hpp \
    $$PWD/autodeletewidgetpointer.h \
    $$PWD/autodeletewidgetpointer.hpp
RESOURCES += ./lon_widget/lon_widget.qrc
