# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


HEADERS += $$PWD/Translate.h
SOURCES += $$PWD/Translate.cpp
RESOURCES += $$PWD/Translate.qrc
